services:
  safedrop:
    build: .
    container_name: SafeDrop
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - /volume2/docker/safedrop/data:/data
      - /volume2/docker/safedrop/public:/app/public
      - /volume2/docker/safedrop/server.js:/app/server.js
      - /volume2/docker/safedrop/package.json:/app/package.json
    environment:
      PORT: "3000"
      DATA_DIR: "/data"
